# Generated by Django 5.0.6 on 2024-06-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomRate',
            fields=[
                ('room_id', models.IntegerField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=100)),
                ('default_rate', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'room_rate',
            },
        ),
    ]
