# Generated by Django 5.0.6 on 2024-06-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_overriddenroomrate_unique_overridden_rate'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='overriddenroomrate',
            name='unique_overridden_rate',
        ),
        migrations.AddConstraint(
            model_name='overriddenroomrate',
            constraint=models.UniqueConstraint(fields=('room_rate', 'stay_date'), name='unique_overridden_rate', violation_error_message='Room rate is already overridden for this date.'),
        ),
    ]
