# Generated by Django 5.0.6 on 2024-06-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_overriddenroomrate_unique_overridden_rate_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='overriddenroomrate',
            name='unique_overridden_rate',
        ),
        migrations.AddConstraint(
            model_name='overriddenroomrate',
            constraint=models.UniqueConstraint(fields=('room_rate', 'stay_date'), name='unique_overridden_rate'),
        ),
    ]
