# Generated by Django 5.0.6 on 2024-06-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_overriddenroomrate_unique_overridden_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('discount_id', models.IntegerField(primary_key=True, serialize=False)),
                ('discount_name', models.CharField(max_length=100)),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], default='fixed', max_length=10)),
                ('default_value', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'discount',
            },
        ),
    ]
