# Generated by Django 5.0.6 on 2024-06-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_default_value_discount_discount_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], default='fixed', error_messages="Invalid choice. Available choices: ['fixed', 'percentage']", max_length=10),
        ),
    ]
