# Generated by Django 5.0.6 on 2024-06-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_discount_discount_type_discountroomrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomrate',
            name='discounts',
            field=models.ManyToManyField(related_name='discount', through='api.DiscountRoomRate', to='api.discount'),
        ),
    ]
